basePath: /fake-api/
consumes:
- application/json
definitions:
  ErrorResponse:
    properties:
      error:
        type: string
        x-go-name: Error
    type: object
    x-go-package: 2-crud/task/put
  Task:
    properties:
      description:
        type: string
        x-go-name: Description
      id:
        format: int64
        type: integer
        x-go-name: ID
      value:
        type: string
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/list
  TaskDeleteResponse:
    properties:
      message:
        type: string
        x-go-name: Message
      status:
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/delete
  TaskGetResponse:
    properties:
      description:
        type: string
        x-go-name: Description
      id:
        format: int64
        type: integer
        x-go-name: ID
      value:
        type: string
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/get
  TaskListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/Task'
        type: array
        x-go-name: List
    type: object
    x-go-package: 2-crud/task/list
  TaskPostRequest:
    properties:
      description:
        type: string
        x-go-name: Description
    type: object
    x-go-package: 2-crud/task/post
  TaskPostResponse:
    properties:
      message:
        type: string
        x-go-name: Message
      status:
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/post
  TaskPutRequest:
    properties:
      description:
        type: string
        x-go-name: Description
      value:
        type: string
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/put
  TaskPutResponse:
    properties:
      status:
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: 2-crud/task/put
host: localhost:8080
info:
  description: Documentation of fake-api.
  title: fake-api.
  version: 0.0.0
paths:
  /task/:
    post:
      operationId: post-task
      parameters:
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/TaskPostRequest'
      responses:
        "201":
          description: TaskPostResponse
          schema:
            $ref: '#/definitions/TaskPostResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Task
  /task/{id}:
    delete:
      operationId: delete-task
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "204":
          description: TaskDeleteResponse
          schema:
            $ref: '#/definitions/TaskDeleteResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Task
    get:
      operationId: get-task
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          description: TaskGetResponse
          schema:
            $ref: '#/definitions/TaskGetResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Task
    put:
      operationId: Put-task
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/TaskPutRequest'
      responses:
        "201":
          description: TaskPutResponse
          schema:
            $ref: '#/definitions/TaskPutResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Task
  /task/list:
    get:
      operationId: list-task
      parameters:
      - in: query
        name: status
        type: string
        x-go-name: Status
      - in: header
        name: x-request-id
        type: string
        x-go-name: XRequestId
      responses:
        "200":
          description: TaskListResponse
          schema:
            $ref: '#/definitions/TaskListResponse'
        "404":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Task
produces:
- application/json
schemes:
- https
swagger: "2.0"
